### ISSUE TITLE
项目收集

### ISSUE THREAD

**Issue by jay-waves** [jay-waves/til#1]
目前发现的几个玩具项目和教程:
1. https://github.com/practical-tutorials/project-based-learning
2. https://github.com/Dor1s/libfuzzer-workshop
3. https://aosabook.org/en/
4. https://github.com/banach-space/llvm-tutor

**Comment by Jay-Waves** [comment]
玩具项目类的程序开发日志可以先发表在这里. 源码放到一个新仓库去, 完善后, 将发表在这里的技术文档当成其 docs
