### ISSUE TITLE
文章收集

### ISSUE THREAD

**Issue by jay-waves** [jay-waves/til#4]
## 并发相关

- [x] Address Sanitizer
- [x] [Thread Sanitizer Algorithm Overview](https://github.com/google/sanitizers/wiki/ThreadSanitizerAlgorithm)
- [x] [ruigulala/ConAnalysis](https://github.com/ruigulala/ConAnalysis/blob/master/conattack.pdf) TSan 扫描, lldb 复现
- [x] ConVul : An Effective Tool for Detecting Concurrency Vulnerabilities (ASE2019) 使用 Intel Pin Framework 插桩, FastTrack 检测竞争事件, 鉴定为屎
- [x] Understanding Real-World Concurrency Bugs in Go (a survey, ASPLOS 2019) 分析介绍go常见漏洞类型
- [ ] Language-based information-flow security (SAC 2003)
- [ ] FastTrack: Efficient and Precise Dynamic Race Detection. 动态事件顺序检测算法, 高引.
- [x] WAFFLE, exposing memory ordering bugs efficiently with active delay injection. 基于 delay-injection 来动态触发竞争
- [x] Eraser: a dynamic data race detector for multithreaded programs. [Savage et al.'97]
- [ ] Time, Clocks, and the Ordering of Events in aDistributed System. [Lamport '78]

**Comment by Jay-Waves** [comment]
## Books: The Architecture of Open Source Applications ([Volume1](https://aosabook.org/))

- [x] [The Bourne-Again Shell (Bash)](https://aosabook.org/en/v1/bash.html)
- [x] LLVM

**Comment by GoesM** [comment]
并发fuzz参考文献推荐：

![1719734951189](https://github.com/jay-waves/til/assets/130988564/c5073ff7-8ddb-4734-b5e4-d46a319ff9be)

**Comment by jay-waves** [comment]
[Let's stop counting centuries](https://dynomight.net/centuries/)

https://corecursive.com/building-powershell-with-jeffrey-snover/#intro

https://blog.sbensu.com/posts/demand-for-visual-programming/

[Seven habits of effective text editing -- Bram Moolenaar](https://www.moolenaar.net/habits.html)

[what's your most productive shortcut with vim](https://stackoverflow.com/questions/1218390/what-is-your-most-productive-shortcut-with-vim/1220118#1220118)
